/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-09-25

******************************************************************************
*/


#include <stm32f10x.h>
#include "app.h"
#include "rtc_f1.h"
#include "timer.h"


int main(void)
{
  RCC_ClocksTypeDef clock;
  RCC_GetClocksFreq(&clock);

  // premapovani JTAG na GPIO
  RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO, ENABLE);
  AFIO->MAPR &= ~AFIO_MAPR_SWJ_CFG;
  AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_JTAGDISABLE;

  App_Init();

//  RTCF1_Test();

  Timer_Delay_ms(1000);
  while (1)
  {
    App_Exec();
  }


}
